'use client'
import { Modal } from '@/components/Modal'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <head />

      <body >
      
          <div className='grid grid-rows-layout max-h-full h-full'>
            <header><Header /></header>
            <main className='mx-auto max-w-[1280px]  w-full flex '>{children}</main>
            <footer className='mx-auto max-w-[1280px] w-full'> <Footer /></footer>
            <Modal />
          </div>
     
      </body>

    </html>

  )
}
